name: base # Always use the `base` environment.
channels:
  - nodefaults # Do not use the default environment.
  - conda-forge # Always use conda-forge instead.
dependencies: # Use conda packages if possible.
  # Requirements not available in the catalog image.
  - hydra-core

  # Essential packages.
  - jemalloc
  - mkl # Intel OpenMP (iomp) and other Intel optimizations depend on MKL.
  - openssh
  - tzdata
