# N.B. Use `awk 'START_LINE<=NR && FINISH_LINE<=NR reqs/simple-environment.yaml'`
# to sort dependencies in the command line while preserving comments, etc.
# N.B. The `conda-lock` command requires the `micromamba` flag to work properly.
# To create a new conda lockfile, use the following command:
# `conda-lock lock --micromamba -f ${CONDA_FILE} -p linux-64 --lockfile ${LOCKFILE}`
name: base # Always use the `base` environment.
channels:
  - nodefaults # Do not use the default environment.
  - conda-forge # Always use conda-forge instead.
  - nvidia # CUDA-related packages are available in the NVIDIA channel.
dependencies: # Use conda packages if possible.
  - python==3.10
  - pytorch::pytorch # Only install PyTorch-related packages from the PyTorch channel.
  - pytorch::torchvision
  - pytorch::pytorch-cuda==11.8
  - jemalloc
  - mkl
  - numpy
  - pytest
  - tmux==3.2a
  - tqdm
