# N.B. Use `awk 'START_LINE<=NR && FINISH_LINE<=NR reqs/simple-environment.yaml'`
# to sort dependencies in the command line while preserving comments, etc.
# N.B. The `conda-lock` command requires the `micromamba` flag to work properly.
# To create a new conda lockfile, use the following command:
# `conda-lock lock --micromamba -f ${CONDA_FILE} -p linux-64 --lockfile ${LOCKFILE}`
name: base # Always use the `base` environment.
channels:
  - nodefaults # Do not use the default channel.
  - conda-forge # Always use conda-forge instead.
dependencies: # Use conda packages if possible.
  - python==3.12
  - jemalloc
  - mkl
  - numpy
  - pytest
  - tmux==3.2a
  - tqdm
  - pip
  - pip:  # PyTorch-related packages should be installed via pip, not conda.
      - torch==2.5.1
      - pyre-check
