# Packages to be installed in `Dockerfile` in `train` mode.
# PyTorch install variables are in the Docker Compose file.
# PyTorch and related libraries are either compiled or installed via pip
# to reduce dependency issues with conda and for greater flexibility.
# Manually add dependencies of compiled libraries for reduced
# installation with pip.
name: base  # Always use the `base` environment.
channels:
  - nodefaults
  - conda-forge
dependencies:  # Use conda packages if possible.
  # Requirements.
  - hydra-core==1.3.1
  - jupyterlab
  - libjpeg-turbo  # Torchvision dependency.
  - libpng  # Torchvision dependency.
  - numpy  # Intel optimized Numpy is not available on PyPI.
  - mkl  # Essential if BUILD_MODE=include and MKL_MODE=include.
  - typing_extensions  # A PyTorch dependency.

  # Utility packages.
  - git
  - jemalloc
#  - libxcb  # Necessary when built from source.

  # `pip` dependencies not available in conda.
  - pip  # Source compiled packages are installed by pip.
  - pip:  # Do not delete this line even if pip packages are not used.
