# Packages to be installed in `Dockerfile` in `train` mode.
# PyTorch install variables are in the Docker Compose file.
# PyTorch and related libraries are either compiled or installed via pip
# to reduce dependency issues with conda and for greater flexibility.
# Manually add dependencies of compiled libraries for reduced
# installation with pip.
name: base # Always use the `base` environment.
channels:
  - nodefaults # Do not use the default environment.
  - conda-forge # Always use conda-forge instead.
dependencies: # Use conda packages if possible.
  # Requirements.
  - hydra-core
  - jupyterlab
  - libjpeg-turbo # TorchVision dependency.
  - libpng # TorchVision dependency.
  - numpy # Intel optimized NumPy is not available on PyPI.
  - mkl # Essential if BUILD_MODE=include and MKL_MODE=include.
  - tqdm
  - typing_extensions # A PyTorch dependency.

  # Essential packages.
  - jemalloc
  - openssh
  - tzdata

  # Utility packages.
  - conda-lock
  - git
  - htop
  - lazygit
  - monkeytype
  - nano
  - pandera
  - parallel
  - pre-commit
  - pytest
  - pytest-xdist
  - rsync
  - shellcheck
  - tree

  # For `pip` dependencies that are not available in conda.
  # Do not delete the `pip` installs even if no `pip` packages are used.
  # Also, do not place anything below the `pip` installs.
  # Source compiled packages are installed via pip.
  - pip
  - pip:
      - hypothesis
      - pyre-check
